### ISSUE TITLE
Peer To Peer Review

### ISSUE THREAD

**Issue by AmineDerbal** [dheerajsachdeva/capstone2#26]
## Highlights :star2: 

- Your modules are organized into folders, which makes them more organized and free of clutter.
- Your code base is readable and neat, and there are no redundant codes.
- You made great use of GitHub flows, which was required.
 - Your design follows the guidelines of the requirements

## Issues ♻️ 

- Kindly change the title of the HTML page to a more suitable one
- Kindly increase the size of your comment form so that it can be read 
- Kindly make separate functions that calculate items and comment number
- Kindly fix the link of your deployed page in the readme file

**Comment by dheerajsachdeva** [comment]
Thanks Amine 😄 

We have made and pull the required changes for these issues.

Thanks and Regards
